# Automatically creates a Product Release PR when anything is committed to v0.7.0.
name: Create Production Release PR

on:
  push:
    branches: [v0.7.0]

jobs:
  create-draft-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Create Production Release PR
        uses: PropellerAero/auto-create-pr-action@master
        env:
          BRANCH_PREFIX: "v0.7.0"
          BASE_BRANCH: "v0.7.0"
          PULL_REQUEST_TITLE: "[Production Release]"
          PULL_REQUEST_DRAFT: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
